"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Direction:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _DirectionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Direction.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EAST: _Direction.ValueType  # 0
    WEST: _Direction.ValueType  # 1
    SOUTH: _Direction.ValueType  # 2
    NORTH: _Direction.ValueType  # 3
    NORTHEAST: _Direction.ValueType  # 4
    SOUTHEAST: _Direction.ValueType  # 5
    SOUTHWEST: _Direction.ValueType  # 6
    NORTHWEST: _Direction.ValueType  # 7
class Direction(_Direction, metaclass=_DirectionEnumTypeWrapper):
    pass

EAST: Direction.ValueType  # 0
WEST: Direction.ValueType  # 1
SOUTH: Direction.ValueType  # 2
NORTH: Direction.ValueType  # 3
NORTHEAST: Direction.ValueType  # 4
SOUTHEAST: Direction.ValueType  # 5
SOUTHWEST: Direction.ValueType  # 6
NORTHWEST: Direction.ValueType  # 7
global___Direction = Direction

