"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import modules.common.proto.header_pb2
import modules.localization.proto.pose_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class DriveEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DriveEvent._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        CRITICAL: DriveEvent._Type.ValueType  # 0
        PROBLEM: DriveEvent._Type.ValueType  # 1
        DESIRED: DriveEvent._Type.ValueType  # 2
        OUT_OF_SCOPE: DriveEvent._Type.ValueType  # 3
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    CRITICAL: DriveEvent.Type.ValueType  # 0
    PROBLEM: DriveEvent.Type.ValueType  # 1
    DESIRED: DriveEvent.Type.ValueType  # 2
    OUT_OF_SCOPE: DriveEvent.Type.ValueType  # 3

    HEADER_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    IS_REPORTABLE_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> modules.common.proto.header_pb2.Header: ...
    event: typing.Text
    @property
    def location(self) -> modules.localization.proto.pose_pb2.Pose: ...
    @property
    def type(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___DriveEvent.Type.ValueType]: ...
    is_reportable: builtins.bool
    def __init__(self,
        *,
        header: typing.Optional[modules.common.proto.header_pb2.Header] = ...,
        event: typing.Optional[typing.Text] = ...,
        location: typing.Optional[modules.localization.proto.pose_pb2.Pose] = ...,
        type: typing.Optional[typing.Iterable[global___DriveEvent.Type.ValueType]] = ...,
        is_reportable: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["event",b"event","header",b"header","is_reportable",b"is_reportable","location",b"location"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["event",b"event","header",b"header","is_reportable",b"is_reportable","location",b"location","type",b"type"]) -> None: ...
global___DriveEvent = DriveEvent
