"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class EngageAdvice(google.protobuf.message.Message):
    """This is the engage advice that published by critical runtime modules."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Advice:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _AdviceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EngageAdvice._Advice.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: EngageAdvice._Advice.ValueType  # 0
        DISALLOW_ENGAGE: EngageAdvice._Advice.ValueType  # 1
        READY_TO_ENGAGE: EngageAdvice._Advice.ValueType  # 2
        KEEP_ENGAGED: EngageAdvice._Advice.ValueType  # 3
        PREPARE_DISENGAGE: EngageAdvice._Advice.ValueType  # 4
    class Advice(_Advice, metaclass=_AdviceEnumTypeWrapper):
        pass

    UNKNOWN: EngageAdvice.Advice.ValueType  # 0
    DISALLOW_ENGAGE: EngageAdvice.Advice.ValueType  # 1
    READY_TO_ENGAGE: EngageAdvice.Advice.ValueType  # 2
    KEEP_ENGAGED: EngageAdvice.Advice.ValueType  # 3
    PREPARE_DISENGAGE: EngageAdvice.Advice.ValueType  # 4

    ADVICE_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    advice: global___EngageAdvice.Advice.ValueType
    reason: typing.Text
    def __init__(self,
        *,
        advice: typing.Optional[global___EngageAdvice.Advice.ValueType] = ...,
        reason: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["advice",b"advice","reason",b"reason"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["advice",b"advice","reason",b"reason"]) -> None: ...
global___EngageAdvice = EngageAdvice
