"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ErrorCode:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ErrorCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ErrorCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OK: _ErrorCode.ValueType  # 0
    """No error, returns on success."""

    CONTROL_ERROR: _ErrorCode.ValueType  # 1000
    """Control module error codes start from here."""

    CONTROL_INIT_ERROR: _ErrorCode.ValueType  # 1001
    CONTROL_COMPUTE_ERROR: _ErrorCode.ValueType  # 1002
    CONTROL_ESTOP_ERROR: _ErrorCode.ValueType  # 1003
    PERFECT_CONTROL_ERROR: _ErrorCode.ValueType  # 1004
    CANBUS_ERROR: _ErrorCode.ValueType  # 2000
    """Canbus module error codes start from here."""

    CAN_CLIENT_ERROR_BASE: _ErrorCode.ValueType  # 2100
    CAN_CLIENT_ERROR_OPEN_DEVICE_FAILED: _ErrorCode.ValueType  # 2101
    CAN_CLIENT_ERROR_FRAME_NUM: _ErrorCode.ValueType  # 2102
    CAN_CLIENT_ERROR_SEND_FAILED: _ErrorCode.ValueType  # 2103
    CAN_CLIENT_ERROR_RECV_FAILED: _ErrorCode.ValueType  # 2104
    LOCALIZATION_ERROR: _ErrorCode.ValueType  # 3000
    """Localization module error codes start from here."""

    LOCALIZATION_ERROR_MSG: _ErrorCode.ValueType  # 3100
    LOCALIZATION_ERROR_LIDAR: _ErrorCode.ValueType  # 3200
    LOCALIZATION_ERROR_INTEG: _ErrorCode.ValueType  # 3300
    LOCALIZATION_ERROR_GNSS: _ErrorCode.ValueType  # 3400
    PERCEPTION_ERROR: _ErrorCode.ValueType  # 4000
    """Perception module error codes start from here."""

    PERCEPTION_ERROR_TF: _ErrorCode.ValueType  # 4001
    PERCEPTION_ERROR_PROCESS: _ErrorCode.ValueType  # 4002
    PERCEPTION_FATAL: _ErrorCode.ValueType  # 4003
    PERCEPTION_ERROR_NONE: _ErrorCode.ValueType  # 4004
    PERCEPTION_ERROR_UNKNOWN: _ErrorCode.ValueType  # 4005
    PREDICTION_ERROR: _ErrorCode.ValueType  # 5000
    """Prediction module error codes start from here."""

    PLANNING_ERROR: _ErrorCode.ValueType  # 6000
    """Planning module error codes start from here"""

    PLANNING_ERROR_NOT_READY: _ErrorCode.ValueType  # 6001
    HDMAP_DATA_ERROR: _ErrorCode.ValueType  # 7000
    """HDMap module error codes start from here"""

    ROUTING_ERROR: _ErrorCode.ValueType  # 8000
    """Routing module error codes"""

    ROUTING_ERROR_REQUEST: _ErrorCode.ValueType  # 8001
    ROUTING_ERROR_RESPONSE: _ErrorCode.ValueType  # 8002
    ROUTING_ERROR_NOT_READY: _ErrorCode.ValueType  # 8003
    END_OF_INPUT: _ErrorCode.ValueType  # 9000
    """Indicates an input has been exhausted."""

    HTTP_LOGIC_ERROR: _ErrorCode.ValueType  # 10000
    """HTTP request error codes."""

    HTTP_RUNTIME_ERROR: _ErrorCode.ValueType  # 10001
    RELATIVE_MAP_ERROR: _ErrorCode.ValueType  # 11000
    """Relative Map error codes.
    general relative map error code
    """

    RELATIVE_MAP_NOT_READY: _ErrorCode.ValueType  # 11001
    DRIVER_ERROR_GNSS: _ErrorCode.ValueType  # 12000
    """Driver error codes."""

    DRIVER_ERROR_VELODYNE: _ErrorCode.ValueType  # 13000
    STORYTELLING_ERROR: _ErrorCode.ValueType  # 14000
    """Storytelling error codes."""

class ErrorCode(_ErrorCode, metaclass=_ErrorCodeEnumTypeWrapper):
    """Error codes enum for API's categorized by modules."""
    pass

OK: ErrorCode.ValueType  # 0
"""No error, returns on success."""

CONTROL_ERROR: ErrorCode.ValueType  # 1000
"""Control module error codes start from here."""

CONTROL_INIT_ERROR: ErrorCode.ValueType  # 1001
CONTROL_COMPUTE_ERROR: ErrorCode.ValueType  # 1002
CONTROL_ESTOP_ERROR: ErrorCode.ValueType  # 1003
PERFECT_CONTROL_ERROR: ErrorCode.ValueType  # 1004
CANBUS_ERROR: ErrorCode.ValueType  # 2000
"""Canbus module error codes start from here."""

CAN_CLIENT_ERROR_BASE: ErrorCode.ValueType  # 2100
CAN_CLIENT_ERROR_OPEN_DEVICE_FAILED: ErrorCode.ValueType  # 2101
CAN_CLIENT_ERROR_FRAME_NUM: ErrorCode.ValueType  # 2102
CAN_CLIENT_ERROR_SEND_FAILED: ErrorCode.ValueType  # 2103
CAN_CLIENT_ERROR_RECV_FAILED: ErrorCode.ValueType  # 2104
LOCALIZATION_ERROR: ErrorCode.ValueType  # 3000
"""Localization module error codes start from here."""

LOCALIZATION_ERROR_MSG: ErrorCode.ValueType  # 3100
LOCALIZATION_ERROR_LIDAR: ErrorCode.ValueType  # 3200
LOCALIZATION_ERROR_INTEG: ErrorCode.ValueType  # 3300
LOCALIZATION_ERROR_GNSS: ErrorCode.ValueType  # 3400
PERCEPTION_ERROR: ErrorCode.ValueType  # 4000
"""Perception module error codes start from here."""

PERCEPTION_ERROR_TF: ErrorCode.ValueType  # 4001
PERCEPTION_ERROR_PROCESS: ErrorCode.ValueType  # 4002
PERCEPTION_FATAL: ErrorCode.ValueType  # 4003
PERCEPTION_ERROR_NONE: ErrorCode.ValueType  # 4004
PERCEPTION_ERROR_UNKNOWN: ErrorCode.ValueType  # 4005
PREDICTION_ERROR: ErrorCode.ValueType  # 5000
"""Prediction module error codes start from here."""

PLANNING_ERROR: ErrorCode.ValueType  # 6000
"""Planning module error codes start from here"""

PLANNING_ERROR_NOT_READY: ErrorCode.ValueType  # 6001
HDMAP_DATA_ERROR: ErrorCode.ValueType  # 7000
"""HDMap module error codes start from here"""

ROUTING_ERROR: ErrorCode.ValueType  # 8000
"""Routing module error codes"""

ROUTING_ERROR_REQUEST: ErrorCode.ValueType  # 8001
ROUTING_ERROR_RESPONSE: ErrorCode.ValueType  # 8002
ROUTING_ERROR_NOT_READY: ErrorCode.ValueType  # 8003
END_OF_INPUT: ErrorCode.ValueType  # 9000
"""Indicates an input has been exhausted."""

HTTP_LOGIC_ERROR: ErrorCode.ValueType  # 10000
"""HTTP request error codes."""

HTTP_RUNTIME_ERROR: ErrorCode.ValueType  # 10001
RELATIVE_MAP_ERROR: ErrorCode.ValueType  # 11000
"""Relative Map error codes.
general relative map error code
"""

RELATIVE_MAP_NOT_READY: ErrorCode.ValueType  # 11001
DRIVER_ERROR_GNSS: ErrorCode.ValueType  # 12000
"""Driver error codes."""

DRIVER_ERROR_VELODYNE: ErrorCode.ValueType  # 13000
STORYTELLING_ERROR: ErrorCode.ValueType  # 14000
"""Storytelling error codes."""

global___ErrorCode = ErrorCode


class StatusPb(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ERROR_CODE_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    error_code: global___ErrorCode.ValueType
    msg: typing.Text
    def __init__(self,
        *,
        error_code: typing.Optional[global___ErrorCode.ValueType] = ...,
        msg: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["error_code",b"error_code","msg",b"msg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_code",b"error_code","msg",b"msg"]) -> None: ...
global___StatusPb = StatusPb
