"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class PointENU(google.protobuf.message.Message):
    """A point in the map reference frame. The map defines an origin, whose
    coordinate is (0, 0, 0).
    Most modules, including localization, perception, and prediction, generate
    results based on the map reference frame.
    Currently, the map uses Universal Transverse Mercator (UTM) projection. See
    the link below for the definition of map origin.
      https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system
    The z field of PointENU can be omitted. If so, it is a 2D location and we do
    not care its height.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    x: builtins.float
    """East from the origin, in meters."""

    y: builtins.float
    """North from the origin, in meters."""

    z: builtins.float
    """Up from the WGS-84 ellipsoid, in"""

    def __init__(self,
        *,
        x: typing.Optional[builtins.float] = ...,
        y: typing.Optional[builtins.float] = ...,
        z: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["x",b"x","y",b"y","z",b"z"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["x",b"x","y",b"y","z",b"z"]) -> None: ...
global___PointENU = PointENU

class PointLLH(google.protobuf.message.Message):
    """A point in the global reference frame. Similar to PointENU, PointLLH allows
    omitting the height field for representing a 2D location.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LON_FIELD_NUMBER: builtins.int
    LAT_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    lon: builtins.float
    """Longitude in degrees, ranging from -180 to 180."""

    lat: builtins.float
    """Latitude in degrees, ranging from -90 to 90."""

    height: builtins.float
    """WGS-84 ellipsoid height in meters."""

    def __init__(self,
        *,
        lon: typing.Optional[builtins.float] = ...,
        lat: typing.Optional[builtins.float] = ...,
        height: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["height",b"height","lat",b"lat","lon",b"lon"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["height",b"height","lat",b"lat","lon",b"lon"]) -> None: ...
global___PointLLH = PointLLH

class Point2D(google.protobuf.message.Message):
    """A general 2D point. Its meaning and units depend on context, and must be
    explained in comments.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    def __init__(self,
        *,
        x: typing.Optional[builtins.float] = ...,
        y: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["x",b"x","y",b"y"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["x",b"x","y",b"y"]) -> None: ...
global___Point2D = Point2D

class Point3D(google.protobuf.message.Message):
    """A general 3D point. Its meaning and units depend on context, and must be
    explained in comments.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    def __init__(self,
        *,
        x: typing.Optional[builtins.float] = ...,
        y: typing.Optional[builtins.float] = ...,
        z: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["x",b"x","y",b"y","z",b"z"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["x",b"x","y",b"y","z",b"z"]) -> None: ...
global___Point3D = Point3D

class Quaternion(google.protobuf.message.Message):
    """A unit quaternion that represents a spatial rotation. See the link below for
    details.
      https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation
    The scalar part qw can be omitted. In this case, qw should be calculated by
      qw = sqrt(1 - qx * qx - qy * qy - qz * qz).
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    QX_FIELD_NUMBER: builtins.int
    QY_FIELD_NUMBER: builtins.int
    QZ_FIELD_NUMBER: builtins.int
    QW_FIELD_NUMBER: builtins.int
    qx: builtins.float
    qy: builtins.float
    qz: builtins.float
    qw: builtins.float
    def __init__(self,
        *,
        qx: typing.Optional[builtins.float] = ...,
        qy: typing.Optional[builtins.float] = ...,
        qz: typing.Optional[builtins.float] = ...,
        qw: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["qw",b"qw","qx",b"qx","qy",b"qy","qz",b"qz"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["qw",b"qw","qx",b"qx","qy",b"qy","qz",b"qz"]) -> None: ...
global___Quaternion = Quaternion

class Polygon(google.protobuf.message.Message):
    """A general polygon, points are counter clockwise"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    POINT_FIELD_NUMBER: builtins.int
    @property
    def point(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Point3D]: ...
    def __init__(self,
        *,
        point: typing.Optional[typing.Iterable[global___Point3D]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["point",b"point"]) -> None: ...
global___Polygon = Polygon
