"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import modules.common.proto.error_code_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Header(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TIMESTAMP_SEC_FIELD_NUMBER: builtins.int
    MODULE_NAME_FIELD_NUMBER: builtins.int
    SEQUENCE_NUM_FIELD_NUMBER: builtins.int
    LIDAR_TIMESTAMP_FIELD_NUMBER: builtins.int
    CAMERA_TIMESTAMP_FIELD_NUMBER: builtins.int
    RADAR_TIMESTAMP_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    FRAME_ID_FIELD_NUMBER: builtins.int
    timestamp_sec: builtins.float
    """Message publishing time in seconds."""

    module_name: typing.Text
    """Module name."""

    sequence_num: builtins.int
    """Sequence number for each message. Each module maintains its own counter for
    sequence_num, always starting from 1 on boot.
    """

    lidar_timestamp: builtins.int
    """Lidar Sensor timestamp for nano-second."""

    camera_timestamp: builtins.int
    """Camera Sensor timestamp for nano-second."""

    radar_timestamp: builtins.int
    """Radar Sensor timestamp for nano-second."""

    version: builtins.int
    """data version"""

    @property
    def status(self) -> modules.common.proto.error_code_pb2.StatusPb: ...
    frame_id: typing.Text
    def __init__(self,
        *,
        timestamp_sec: typing.Optional[builtins.float] = ...,
        module_name: typing.Optional[typing.Text] = ...,
        sequence_num: typing.Optional[builtins.int] = ...,
        lidar_timestamp: typing.Optional[builtins.int] = ...,
        camera_timestamp: typing.Optional[builtins.int] = ...,
        radar_timestamp: typing.Optional[builtins.int] = ...,
        version: typing.Optional[builtins.int] = ...,
        status: typing.Optional[modules.common.proto.error_code_pb2.StatusPb] = ...,
        frame_id: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["camera_timestamp",b"camera_timestamp","frame_id",b"frame_id","lidar_timestamp",b"lidar_timestamp","module_name",b"module_name","radar_timestamp",b"radar_timestamp","sequence_num",b"sequence_num","status",b"status","timestamp_sec",b"timestamp_sec","version",b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["camera_timestamp",b"camera_timestamp","frame_id",b"frame_id","lidar_timestamp",b"lidar_timestamp","module_name",b"module_name","radar_timestamp",b"radar_timestamp","sequence_num",b"sequence_num","status",b"status","timestamp_sec",b"timestamp_sec","version",b"version"]) -> None: ...
global___Header = Header
