"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class SLPoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    S_FIELD_NUMBER: builtins.int
    L_FIELD_NUMBER: builtins.int
    s: builtins.float
    l: builtins.float
    def __init__(self,
        *,
        s: typing.Optional[builtins.float] = ...,
        l: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["l",b"l","s",b"s"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["l",b"l","s",b"s"]) -> None: ...
global___SLPoint = SLPoint

class FrenetFramePoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    S_FIELD_NUMBER: builtins.int
    L_FIELD_NUMBER: builtins.int
    DL_FIELD_NUMBER: builtins.int
    DDL_FIELD_NUMBER: builtins.int
    s: builtins.float
    l: builtins.float
    dl: builtins.float
    ddl: builtins.float
    def __init__(self,
        *,
        s: typing.Optional[builtins.float] = ...,
        l: typing.Optional[builtins.float] = ...,
        dl: typing.Optional[builtins.float] = ...,
        ddl: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ddl",b"ddl","dl",b"dl","l",b"l","s",b"s"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ddl",b"ddl","dl",b"dl","l",b"l","s",b"s"]) -> None: ...
global___FrenetFramePoint = FrenetFramePoint

class SpeedPoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    S_FIELD_NUMBER: builtins.int
    T_FIELD_NUMBER: builtins.int
    V_FIELD_NUMBER: builtins.int
    A_FIELD_NUMBER: builtins.int
    DA_FIELD_NUMBER: builtins.int
    s: builtins.float
    t: builtins.float
    v: builtins.float
    """speed (m/s)"""

    a: builtins.float
    """acceleration (m/s^2)"""

    da: builtins.float
    """jerk (m/s^3)"""

    def __init__(self,
        *,
        s: typing.Optional[builtins.float] = ...,
        t: typing.Optional[builtins.float] = ...,
        v: typing.Optional[builtins.float] = ...,
        a: typing.Optional[builtins.float] = ...,
        da: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["a",b"a","da",b"da","s",b"s","t",b"t","v",b"v"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["a",b"a","da",b"da","s",b"s","t",b"t","v",b"v"]) -> None: ...
global___SpeedPoint = SpeedPoint

class PathPoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    THETA_FIELD_NUMBER: builtins.int
    KAPPA_FIELD_NUMBER: builtins.int
    S_FIELD_NUMBER: builtins.int
    DKAPPA_FIELD_NUMBER: builtins.int
    DDKAPPA_FIELD_NUMBER: builtins.int
    LANE_ID_FIELD_NUMBER: builtins.int
    X_DERIVATIVE_FIELD_NUMBER: builtins.int
    Y_DERIVATIVE_FIELD_NUMBER: builtins.int
    x: builtins.float
    """coordinates"""

    y: builtins.float
    z: builtins.float
    theta: builtins.float
    """direction on the x-y plane"""

    kappa: builtins.float
    """curvature on the x-y planning"""

    s: builtins.float
    """accumulated distance from beginning of the path"""

    dkappa: builtins.float
    """derivative of kappa w.r.t s."""

    ddkappa: builtins.float
    """derivative of derivative of kappa w.r.t s."""

    lane_id: typing.Text
    """The lane ID where the path point is on"""

    x_derivative: builtins.float
    """derivative of x and y w.r.t parametric parameter t in CosThetareferenceline"""

    y_derivative: builtins.float
    def __init__(self,
        *,
        x: typing.Optional[builtins.float] = ...,
        y: typing.Optional[builtins.float] = ...,
        z: typing.Optional[builtins.float] = ...,
        theta: typing.Optional[builtins.float] = ...,
        kappa: typing.Optional[builtins.float] = ...,
        s: typing.Optional[builtins.float] = ...,
        dkappa: typing.Optional[builtins.float] = ...,
        ddkappa: typing.Optional[builtins.float] = ...,
        lane_id: typing.Optional[typing.Text] = ...,
        x_derivative: typing.Optional[builtins.float] = ...,
        y_derivative: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["ddkappa",b"ddkappa","dkappa",b"dkappa","kappa",b"kappa","lane_id",b"lane_id","s",b"s","theta",b"theta","x",b"x","x_derivative",b"x_derivative","y",b"y","y_derivative",b"y_derivative","z",b"z"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["ddkappa",b"ddkappa","dkappa",b"dkappa","kappa",b"kappa","lane_id",b"lane_id","s",b"s","theta",b"theta","x",b"x","x_derivative",b"x_derivative","y",b"y","y_derivative",b"y_derivative","z",b"z"]) -> None: ...
global___PathPoint = PathPoint

class Path(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    PATH_POINT_FIELD_NUMBER: builtins.int
    name: typing.Text
    @property
    def path_point(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PathPoint]: ...
    def __init__(self,
        *,
        name: typing.Optional[typing.Text] = ...,
        path_point: typing.Optional[typing.Iterable[global___PathPoint]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["name",b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","path_point",b"path_point"]) -> None: ...
global___Path = Path

class TrajectoryPoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PATH_POINT_FIELD_NUMBER: builtins.int
    V_FIELD_NUMBER: builtins.int
    A_FIELD_NUMBER: builtins.int
    RELATIVE_TIME_FIELD_NUMBER: builtins.int
    DA_FIELD_NUMBER: builtins.int
    STEER_FIELD_NUMBER: builtins.int
    GAUSSIAN_INFO_FIELD_NUMBER: builtins.int
    @property
    def path_point(self) -> global___PathPoint:
        """path point"""
        pass
    v: builtins.float
    """linear velocity
    in [m/s]
    """

    a: builtins.float
    """linear acceleration"""

    relative_time: builtins.float
    """relative time from beginning of the trajectory"""

    da: builtins.float
    """longitudinal jerk"""

    steer: builtins.float
    """The angle between vehicle front wheel and vehicle longitudinal axis"""

    @property
    def gaussian_info(self) -> global___GaussianInfo:
        """Gaussian probability information"""
        pass
    def __init__(self,
        *,
        path_point: typing.Optional[global___PathPoint] = ...,
        v: typing.Optional[builtins.float] = ...,
        a: typing.Optional[builtins.float] = ...,
        relative_time: typing.Optional[builtins.float] = ...,
        da: typing.Optional[builtins.float] = ...,
        steer: typing.Optional[builtins.float] = ...,
        gaussian_info: typing.Optional[global___GaussianInfo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["a",b"a","da",b"da","gaussian_info",b"gaussian_info","path_point",b"path_point","relative_time",b"relative_time","steer",b"steer","v",b"v"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["a",b"a","da",b"da","gaussian_info",b"gaussian_info","path_point",b"path_point","relative_time",b"relative_time","steer",b"steer","v",b"v"]) -> None: ...
global___TrajectoryPoint = TrajectoryPoint

class Trajectory(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    TRAJECTORY_POINT_FIELD_NUMBER: builtins.int
    name: typing.Text
    @property
    def trajectory_point(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TrajectoryPoint]: ...
    def __init__(self,
        *,
        name: typing.Optional[typing.Text] = ...,
        trajectory_point: typing.Optional[typing.Iterable[global___TrajectoryPoint]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["name",b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","trajectory_point",b"trajectory_point"]) -> None: ...
global___Trajectory = Trajectory

class VehicleMotionPoint(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TRAJECTORY_POINT_FIELD_NUMBER: builtins.int
    STEER_FIELD_NUMBER: builtins.int
    @property
    def trajectory_point(self) -> global___TrajectoryPoint:
        """trajectory point"""
        pass
    steer: builtins.float
    """The angle between vehicle front wheel and vehicle longitudinal axis"""

    def __init__(self,
        *,
        trajectory_point: typing.Optional[global___TrajectoryPoint] = ...,
        steer: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["steer",b"steer","trajectory_point",b"trajectory_point"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["steer",b"steer","trajectory_point",b"trajectory_point"]) -> None: ...
global___VehicleMotionPoint = VehicleMotionPoint

class VehicleMotion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    VEHICLE_MOTION_POINT_FIELD_NUMBER: builtins.int
    name: typing.Text
    @property
    def vehicle_motion_point(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___VehicleMotionPoint]: ...
    def __init__(self,
        *,
        name: typing.Optional[typing.Text] = ...,
        vehicle_motion_point: typing.Optional[typing.Iterable[global___VehicleMotionPoint]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["name",b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","vehicle_motion_point",b"vehicle_motion_point"]) -> None: ...
global___VehicleMotion = VehicleMotion

class GaussianInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SIGMA_X_FIELD_NUMBER: builtins.int
    SIGMA_Y_FIELD_NUMBER: builtins.int
    CORRELATION_FIELD_NUMBER: builtins.int
    AREA_PROBABILITY_FIELD_NUMBER: builtins.int
    ELLIPSE_A_FIELD_NUMBER: builtins.int
    ELLIPSE_B_FIELD_NUMBER: builtins.int
    THETA_A_FIELD_NUMBER: builtins.int
    sigma_x: builtins.float
    """Information of gaussian distribution"""

    sigma_y: builtins.float
    correlation: builtins.float
    area_probability: builtins.float
    """Information of representative uncertainty area"""

    ellipse_a: builtins.float
    ellipse_b: builtins.float
    theta_a: builtins.float
    def __init__(self,
        *,
        sigma_x: typing.Optional[builtins.float] = ...,
        sigma_y: typing.Optional[builtins.float] = ...,
        correlation: typing.Optional[builtins.float] = ...,
        area_probability: typing.Optional[builtins.float] = ...,
        ellipse_a: typing.Optional[builtins.float] = ...,
        ellipse_b: typing.Optional[builtins.float] = ...,
        theta_a: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["area_probability",b"area_probability","correlation",b"correlation","ellipse_a",b"ellipse_a","ellipse_b",b"ellipse_b","sigma_x",b"sigma_x","sigma_y",b"sigma_y","theta_a",b"theta_a"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["area_probability",b"area_probability","correlation",b"correlation","ellipse_a",b"ellipse_a","ellipse_b",b"ellipse_b","sigma_x",b"sigma_x","sigma_y",b"sigma_y","theta_a",b"theta_a"]) -> None: ...
global___GaussianInfo = GaussianInfo
