"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class VehicleSignal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _TurnSignal:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TurnSignalEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[VehicleSignal._TurnSignal.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TURN_NONE: VehicleSignal._TurnSignal.ValueType  # 0
        TURN_LEFT: VehicleSignal._TurnSignal.ValueType  # 1
        TURN_RIGHT: VehicleSignal._TurnSignal.ValueType  # 2
    class TurnSignal(_TurnSignal, metaclass=_TurnSignalEnumTypeWrapper):
        pass

    TURN_NONE: VehicleSignal.TurnSignal.ValueType  # 0
    TURN_LEFT: VehicleSignal.TurnSignal.ValueType  # 1
    TURN_RIGHT: VehicleSignal.TurnSignal.ValueType  # 2

    TURN_SIGNAL_FIELD_NUMBER: builtins.int
    HIGH_BEAM_FIELD_NUMBER: builtins.int
    LOW_BEAM_FIELD_NUMBER: builtins.int
    HORN_FIELD_NUMBER: builtins.int
    EMERGENCY_LIGHT_FIELD_NUMBER: builtins.int
    turn_signal: global___VehicleSignal.TurnSignal.ValueType
    high_beam: builtins.bool
    """lights enable command"""

    low_beam: builtins.bool
    horn: builtins.bool
    emergency_light: builtins.bool
    def __init__(self,
        *,
        turn_signal: typing.Optional[global___VehicleSignal.TurnSignal.ValueType] = ...,
        high_beam: typing.Optional[builtins.bool] = ...,
        low_beam: typing.Optional[builtins.bool] = ...,
        horn: typing.Optional[builtins.bool] = ...,
        emergency_light: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["emergency_light",b"emergency_light","high_beam",b"high_beam","horn",b"horn","low_beam",b"low_beam","turn_signal",b"turn_signal"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["emergency_light",b"emergency_light","high_beam",b"high_beam","horn",b"horn","low_beam",b"low_beam","turn_signal",b"turn_signal"]) -> None: ...
global___VehicleSignal = VehicleSignal
