"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import modules.map.proto.map_geometry_pb2
import modules.map.proto.map_id_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class LaneBoundaryType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LaneBoundaryType._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: LaneBoundaryType._Type.ValueType  # 0
        DOTTED_YELLOW: LaneBoundaryType._Type.ValueType  # 1
        DOTTED_WHITE: LaneBoundaryType._Type.ValueType  # 2
        SOLID_YELLOW: LaneBoundaryType._Type.ValueType  # 3
        SOLID_WHITE: LaneBoundaryType._Type.ValueType  # 4
        DOUBLE_YELLOW: LaneBoundaryType._Type.ValueType  # 5
        CURB: LaneBoundaryType._Type.ValueType  # 6
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    UNKNOWN: LaneBoundaryType.Type.ValueType  # 0
    DOTTED_YELLOW: LaneBoundaryType.Type.ValueType  # 1
    DOTTED_WHITE: LaneBoundaryType.Type.ValueType  # 2
    SOLID_YELLOW: LaneBoundaryType.Type.ValueType  # 3
    SOLID_WHITE: LaneBoundaryType.Type.ValueType  # 4
    DOUBLE_YELLOW: LaneBoundaryType.Type.ValueType  # 5
    CURB: LaneBoundaryType.Type.ValueType  # 6

    S_FIELD_NUMBER: builtins.int
    TYPES_FIELD_NUMBER: builtins.int
    s: builtins.float
    """Offset relative to the starting point of boundary"""

    @property
    def types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___LaneBoundaryType.Type.ValueType]:
        """support multiple types"""
        pass
    def __init__(self,
        *,
        s: typing.Optional[builtins.float] = ...,
        types: typing.Optional[typing.Iterable[global___LaneBoundaryType.Type.ValueType]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["s",b"s"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["s",b"s","types",b"types"]) -> None: ...
global___LaneBoundaryType = LaneBoundaryType

class LaneBoundary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CURVE_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    VIRTUAL_FIELD_NUMBER: builtins.int
    BOUNDARY_TYPE_FIELD_NUMBER: builtins.int
    @property
    def curve(self) -> modules.map.proto.map_geometry_pb2.Curve: ...
    length: builtins.float
    virtual: builtins.bool
    """indicate whether the lane boundary exists in real world"""

    @property
    def boundary_type(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LaneBoundaryType]:
        """in ascending order of s"""
        pass
    def __init__(self,
        *,
        curve: typing.Optional[modules.map.proto.map_geometry_pb2.Curve] = ...,
        length: typing.Optional[builtins.float] = ...,
        virtual: typing.Optional[builtins.bool] = ...,
        boundary_type: typing.Optional[typing.Iterable[global___LaneBoundaryType]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["curve",b"curve","length",b"length","virtual",b"virtual"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["boundary_type",b"boundary_type","curve",b"curve","length",b"length","virtual",b"virtual"]) -> None: ...
global___LaneBoundary = LaneBoundary

class LaneSampleAssociation(google.protobuf.message.Message):
    """Association between central point to closest boundary."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    S_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    s: builtins.float
    width: builtins.float
    def __init__(self,
        *,
        s: typing.Optional[builtins.float] = ...,
        width: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["s",b"s","width",b"width"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["s",b"s","width",b"width"]) -> None: ...
global___LaneSampleAssociation = LaneSampleAssociation

class Lane(google.protobuf.message.Message):
    """A lane is part of a roadway, that is designated for use by a single line of
    vehicles.
    Most public roads (include highways) have more than two lanes.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _LaneType:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _LaneTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Lane._LaneType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NONE: Lane._LaneType.ValueType  # 1
        CITY_DRIVING: Lane._LaneType.ValueType  # 2
        BIKING: Lane._LaneType.ValueType  # 3
        SIDEWALK: Lane._LaneType.ValueType  # 4
        PARKING: Lane._LaneType.ValueType  # 5
        SHOULDER: Lane._LaneType.ValueType  # 6
    class LaneType(_LaneType, metaclass=_LaneTypeEnumTypeWrapper):
        pass

    NONE: Lane.LaneType.ValueType  # 1
    CITY_DRIVING: Lane.LaneType.ValueType  # 2
    BIKING: Lane.LaneType.ValueType  # 3
    SIDEWALK: Lane.LaneType.ValueType  # 4
    PARKING: Lane.LaneType.ValueType  # 5
    SHOULDER: Lane.LaneType.ValueType  # 6

    class _LaneTurn:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _LaneTurnEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Lane._LaneTurn.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NO_TURN: Lane._LaneTurn.ValueType  # 1
        LEFT_TURN: Lane._LaneTurn.ValueType  # 2
        RIGHT_TURN: Lane._LaneTurn.ValueType  # 3
        U_TURN: Lane._LaneTurn.ValueType  # 4
    class LaneTurn(_LaneTurn, metaclass=_LaneTurnEnumTypeWrapper):
        pass

    NO_TURN: Lane.LaneTurn.ValueType  # 1
    LEFT_TURN: Lane.LaneTurn.ValueType  # 2
    RIGHT_TURN: Lane.LaneTurn.ValueType  # 3
    U_TURN: Lane.LaneTurn.ValueType  # 4

    class _LaneDirection:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _LaneDirectionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Lane._LaneDirection.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        FORWARD: Lane._LaneDirection.ValueType  # 1
        BACKWARD: Lane._LaneDirection.ValueType  # 2
        BIDIRECTION: Lane._LaneDirection.ValueType  # 3
    class LaneDirection(_LaneDirection, metaclass=_LaneDirectionEnumTypeWrapper):
        pass

    FORWARD: Lane.LaneDirection.ValueType  # 1
    BACKWARD: Lane.LaneDirection.ValueType  # 2
    BIDIRECTION: Lane.LaneDirection.ValueType  # 3

    ID_FIELD_NUMBER: builtins.int
    CENTRAL_CURVE_FIELD_NUMBER: builtins.int
    LEFT_BOUNDARY_FIELD_NUMBER: builtins.int
    RIGHT_BOUNDARY_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    SPEED_LIMIT_FIELD_NUMBER: builtins.int
    OVERLAP_ID_FIELD_NUMBER: builtins.int
    PREDECESSOR_ID_FIELD_NUMBER: builtins.int
    SUCCESSOR_ID_FIELD_NUMBER: builtins.int
    LEFT_NEIGHBOR_FORWARD_LANE_ID_FIELD_NUMBER: builtins.int
    RIGHT_NEIGHBOR_FORWARD_LANE_ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    TURN_FIELD_NUMBER: builtins.int
    LEFT_NEIGHBOR_REVERSE_LANE_ID_FIELD_NUMBER: builtins.int
    RIGHT_NEIGHBOR_REVERSE_LANE_ID_FIELD_NUMBER: builtins.int
    JUNCTION_ID_FIELD_NUMBER: builtins.int
    LEFT_SAMPLE_FIELD_NUMBER: builtins.int
    RIGHT_SAMPLE_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    LEFT_ROAD_SAMPLE_FIELD_NUMBER: builtins.int
    RIGHT_ROAD_SAMPLE_FIELD_NUMBER: builtins.int
    SELF_REVERSE_LANE_ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def central_curve(self) -> modules.map.proto.map_geometry_pb2.Curve:
        """Central lane as reference trajectory, not necessary to be the geometry
        central.
        """
        pass
    @property
    def left_boundary(self) -> global___LaneBoundary:
        """Lane boundary curve."""
        pass
    @property
    def right_boundary(self) -> global___LaneBoundary: ...
    length: builtins.float
    """in meters."""

    speed_limit: builtins.float
    """Speed limit of the lane, in meters per second."""

    @property
    def overlap_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    @property
    def predecessor_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]:
        """All lanes can be driving into (or from)."""
        pass
    @property
    def successor_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    @property
    def left_neighbor_forward_lane_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]:
        """Neighbor lanes on the same direction."""
        pass
    @property
    def right_neighbor_forward_lane_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    type: global___Lane.LaneType.ValueType
    turn: global___Lane.LaneTurn.ValueType
    @property
    def left_neighbor_reverse_lane_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    @property
    def right_neighbor_reverse_lane_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    @property
    def junction_id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def left_sample(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LaneSampleAssociation]:
        """Association between central point to closest boundary."""
        pass
    @property
    def right_sample(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LaneSampleAssociation]: ...
    direction: global___Lane.LaneDirection.ValueType
    @property
    def left_road_sample(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LaneSampleAssociation]:
        """Association between central point to closest road boundary."""
        pass
    @property
    def right_road_sample(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LaneSampleAssociation]: ...
    @property
    def self_reverse_lane_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        central_curve: typing.Optional[modules.map.proto.map_geometry_pb2.Curve] = ...,
        left_boundary: typing.Optional[global___LaneBoundary] = ...,
        right_boundary: typing.Optional[global___LaneBoundary] = ...,
        length: typing.Optional[builtins.float] = ...,
        speed_limit: typing.Optional[builtins.float] = ...,
        overlap_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        predecessor_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        successor_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        left_neighbor_forward_lane_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        right_neighbor_forward_lane_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        type: typing.Optional[global___Lane.LaneType.ValueType] = ...,
        turn: typing.Optional[global___Lane.LaneTurn.ValueType] = ...,
        left_neighbor_reverse_lane_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        right_neighbor_reverse_lane_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        junction_id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        left_sample: typing.Optional[typing.Iterable[global___LaneSampleAssociation]] = ...,
        right_sample: typing.Optional[typing.Iterable[global___LaneSampleAssociation]] = ...,
        direction: typing.Optional[global___Lane.LaneDirection.ValueType] = ...,
        left_road_sample: typing.Optional[typing.Iterable[global___LaneSampleAssociation]] = ...,
        right_road_sample: typing.Optional[typing.Iterable[global___LaneSampleAssociation]] = ...,
        self_reverse_lane_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["central_curve",b"central_curve","direction",b"direction","id",b"id","junction_id",b"junction_id","left_boundary",b"left_boundary","length",b"length","right_boundary",b"right_boundary","speed_limit",b"speed_limit","turn",b"turn","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["central_curve",b"central_curve","direction",b"direction","id",b"id","junction_id",b"junction_id","left_boundary",b"left_boundary","left_neighbor_forward_lane_id",b"left_neighbor_forward_lane_id","left_neighbor_reverse_lane_id",b"left_neighbor_reverse_lane_id","left_road_sample",b"left_road_sample","left_sample",b"left_sample","length",b"length","overlap_id",b"overlap_id","predecessor_id",b"predecessor_id","right_boundary",b"right_boundary","right_neighbor_forward_lane_id",b"right_neighbor_forward_lane_id","right_neighbor_reverse_lane_id",b"right_neighbor_reverse_lane_id","right_road_sample",b"right_road_sample","right_sample",b"right_sample","self_reverse_lane_id",b"self_reverse_lane_id","speed_limit",b"speed_limit","successor_id",b"successor_id","turn",b"turn","type",b"type"]) -> None: ...
global___Lane = Lane
