"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import modules.map.proto.map_geometry_pb2
import modules.map.proto.map_id_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class LaneOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    START_S_FIELD_NUMBER: builtins.int
    END_S_FIELD_NUMBER: builtins.int
    IS_MERGE_FIELD_NUMBER: builtins.int
    REGION_OVERLAP_ID_FIELD_NUMBER: builtins.int
    start_s: builtins.float
    """position (s-coordinate)"""

    end_s: builtins.float
    """position (s-coordinate)"""

    is_merge: builtins.bool
    @property
    def region_overlap_id(self) -> modules.map.proto.map_id_pb2.Id: ...
    def __init__(self,
        *,
        start_s: typing.Optional[builtins.float] = ...,
        end_s: typing.Optional[builtins.float] = ...,
        is_merge: typing.Optional[builtins.bool] = ...,
        region_overlap_id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["end_s",b"end_s","is_merge",b"is_merge","region_overlap_id",b"region_overlap_id","start_s",b"start_s"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["end_s",b"end_s","is_merge",b"is_merge","region_overlap_id",b"region_overlap_id","start_s",b"start_s"]) -> None: ...
global___LaneOverlapInfo = LaneOverlapInfo

class SignalOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___SignalOverlapInfo = SignalOverlapInfo

class StopSignOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___StopSignOverlapInfo = StopSignOverlapInfo

class CrosswalkOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    REGION_OVERLAP_ID_FIELD_NUMBER: builtins.int
    @property
    def region_overlap_id(self) -> modules.map.proto.map_id_pb2.Id: ...
    def __init__(self,
        *,
        region_overlap_id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["region_overlap_id",b"region_overlap_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["region_overlap_id",b"region_overlap_id"]) -> None: ...
global___CrosswalkOverlapInfo = CrosswalkOverlapInfo

class JunctionOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___JunctionOverlapInfo = JunctionOverlapInfo

class YieldOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___YieldOverlapInfo = YieldOverlapInfo

class ClearAreaOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ClearAreaOverlapInfo = ClearAreaOverlapInfo

class SpeedBumpOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___SpeedBumpOverlapInfo = SpeedBumpOverlapInfo

class ParkingSpaceOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ParkingSpaceOverlapInfo = ParkingSpaceOverlapInfo

class PNCJunctionOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___PNCJunctionOverlapInfo = PNCJunctionOverlapInfo

class RSUOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___RSUOverlapInfo = RSUOverlapInfo

class RegionOverlapInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POLYGON_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def polygon(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_geometry_pb2.Polygon]: ...
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        polygon: typing.Optional[typing.Iterable[modules.map.proto.map_geometry_pb2.Polygon]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","polygon",b"polygon"]) -> None: ...
global___RegionOverlapInfo = RegionOverlapInfo

class ObjectOverlapInfo(google.protobuf.message.Message):
    """Information about one object in the overlap."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    LANE_OVERLAP_INFO_FIELD_NUMBER: builtins.int
    SIGNAL_OVERLAP_INFO_FIELD_NUMBER: builtins.int
    STOP_SIGN_OVERLAP_INFO_FIELD_NUMBER: builtins.int
    CROSSWALK_OVERLAP_INFO_FIELD_NUMBER: builtins.int
    JUNCTION_OVERLAP_INFO_FIELD_NUMBER: builtins.int
    YIELD_SIGN_OVERLAP_INFO_FIELD_NUMBER: builtins.int
    CLEAR_AREA_OVERLAP_INFO_FIELD_NUMBER: builtins.int
    SPEED_BUMP_OVERLAP_INFO_FIELD_NUMBER: builtins.int
    PARKING_SPACE_OVERLAP_INFO_FIELD_NUMBER: builtins.int
    PNC_JUNCTION_OVERLAP_INFO_FIELD_NUMBER: builtins.int
    RSU_OVERLAP_INFO_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def lane_overlap_info(self) -> global___LaneOverlapInfo: ...
    @property
    def signal_overlap_info(self) -> global___SignalOverlapInfo: ...
    @property
    def stop_sign_overlap_info(self) -> global___StopSignOverlapInfo: ...
    @property
    def crosswalk_overlap_info(self) -> global___CrosswalkOverlapInfo: ...
    @property
    def junction_overlap_info(self) -> global___JunctionOverlapInfo: ...
    @property
    def yield_sign_overlap_info(self) -> global___YieldOverlapInfo: ...
    @property
    def clear_area_overlap_info(self) -> global___ClearAreaOverlapInfo: ...
    @property
    def speed_bump_overlap_info(self) -> global___SpeedBumpOverlapInfo: ...
    @property
    def parking_space_overlap_info(self) -> global___ParkingSpaceOverlapInfo: ...
    @property
    def pnc_junction_overlap_info(self) -> global___PNCJunctionOverlapInfo: ...
    @property
    def rsu_overlap_info(self) -> global___RSUOverlapInfo: ...
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        lane_overlap_info: typing.Optional[global___LaneOverlapInfo] = ...,
        signal_overlap_info: typing.Optional[global___SignalOverlapInfo] = ...,
        stop_sign_overlap_info: typing.Optional[global___StopSignOverlapInfo] = ...,
        crosswalk_overlap_info: typing.Optional[global___CrosswalkOverlapInfo] = ...,
        junction_overlap_info: typing.Optional[global___JunctionOverlapInfo] = ...,
        yield_sign_overlap_info: typing.Optional[global___YieldOverlapInfo] = ...,
        clear_area_overlap_info: typing.Optional[global___ClearAreaOverlapInfo] = ...,
        speed_bump_overlap_info: typing.Optional[global___SpeedBumpOverlapInfo] = ...,
        parking_space_overlap_info: typing.Optional[global___ParkingSpaceOverlapInfo] = ...,
        pnc_junction_overlap_info: typing.Optional[global___PNCJunctionOverlapInfo] = ...,
        rsu_overlap_info: typing.Optional[global___RSUOverlapInfo] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["clear_area_overlap_info",b"clear_area_overlap_info","crosswalk_overlap_info",b"crosswalk_overlap_info","id",b"id","junction_overlap_info",b"junction_overlap_info","lane_overlap_info",b"lane_overlap_info","overlap_info",b"overlap_info","parking_space_overlap_info",b"parking_space_overlap_info","pnc_junction_overlap_info",b"pnc_junction_overlap_info","rsu_overlap_info",b"rsu_overlap_info","signal_overlap_info",b"signal_overlap_info","speed_bump_overlap_info",b"speed_bump_overlap_info","stop_sign_overlap_info",b"stop_sign_overlap_info","yield_sign_overlap_info",b"yield_sign_overlap_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clear_area_overlap_info",b"clear_area_overlap_info","crosswalk_overlap_info",b"crosswalk_overlap_info","id",b"id","junction_overlap_info",b"junction_overlap_info","lane_overlap_info",b"lane_overlap_info","overlap_info",b"overlap_info","parking_space_overlap_info",b"parking_space_overlap_info","pnc_junction_overlap_info",b"pnc_junction_overlap_info","rsu_overlap_info",b"rsu_overlap_info","signal_overlap_info",b"signal_overlap_info","speed_bump_overlap_info",b"speed_bump_overlap_info","stop_sign_overlap_info",b"stop_sign_overlap_info","yield_sign_overlap_info",b"yield_sign_overlap_info"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["overlap_info",b"overlap_info"]) -> typing.Optional[typing_extensions.Literal["lane_overlap_info","signal_overlap_info","stop_sign_overlap_info","crosswalk_overlap_info","junction_overlap_info","yield_sign_overlap_info","clear_area_overlap_info","speed_bump_overlap_info","parking_space_overlap_info","pnc_junction_overlap_info","rsu_overlap_info"]]: ...
global___ObjectOverlapInfo = ObjectOverlapInfo

class Overlap(google.protobuf.message.Message):
    """Here, the "overlap" includes any pair of objects on the map
    (e.g. lanes, junctions, and crosswalks).
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    OBJECT_FIELD_NUMBER: builtins.int
    REGION_OVERLAP_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def object(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ObjectOverlapInfo]:
        """Information about one overlap, include all overlapped objects."""
        pass
    @property
    def region_overlap(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RegionOverlapInfo]: ...
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        object: typing.Optional[typing.Iterable[global___ObjectOverlapInfo]] = ...,
        region_overlap: typing.Optional[typing.Iterable[global___RegionOverlapInfo]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","object",b"object","region_overlap",b"region_overlap"]) -> None: ...
global___Overlap = Overlap
