"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import modules.map.proto.map_id_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class RSU(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    JUNCTION_ID_FIELD_NUMBER: builtins.int
    OVERLAP_ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def junction_id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def overlap_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        junction_id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        overlap_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","junction_id",b"junction_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","junction_id",b"junction_id","overlap_id",b"overlap_id"]) -> None: ...
global___RSU = RSU
