"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import modules.common.proto.geometry_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Polygon(google.protobuf.message.Message):
    """Polygon, not necessary convex."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    POINT_FIELD_NUMBER: builtins.int
    @property
    def point(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.common.proto.geometry_pb2.PointENU]: ...
    def __init__(self,
        *,
        point: typing.Optional[typing.Iterable[modules.common.proto.geometry_pb2.PointENU]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["point",b"point"]) -> None: ...
global___Polygon = Polygon

class LineSegment(google.protobuf.message.Message):
    """Straight line segment."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    POINT_FIELD_NUMBER: builtins.int
    @property
    def point(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.common.proto.geometry_pb2.PointENU]: ...
    def __init__(self,
        *,
        point: typing.Optional[typing.Iterable[modules.common.proto.geometry_pb2.PointENU]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["point",b"point"]) -> None: ...
global___LineSegment = LineSegment

class CurveSegment(google.protobuf.message.Message):
    """Generalization of a line."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LINE_SEGMENT_FIELD_NUMBER: builtins.int
    S_FIELD_NUMBER: builtins.int
    START_POSITION_FIELD_NUMBER: builtins.int
    HEADING_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    @property
    def line_segment(self) -> global___LineSegment: ...
    s: builtins.float
    """start position (s-coordinate)"""

    @property
    def start_position(self) -> modules.common.proto.geometry_pb2.PointENU: ...
    heading: builtins.float
    """start orientation"""

    length: builtins.float
    def __init__(self,
        *,
        line_segment: typing.Optional[global___LineSegment] = ...,
        s: typing.Optional[builtins.float] = ...,
        start_position: typing.Optional[modules.common.proto.geometry_pb2.PointENU] = ...,
        heading: typing.Optional[builtins.float] = ...,
        length: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["curve_type",b"curve_type","heading",b"heading","length",b"length","line_segment",b"line_segment","s",b"s","start_position",b"start_position"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["curve_type",b"curve_type","heading",b"heading","length",b"length","line_segment",b"line_segment","s",b"s","start_position",b"start_position"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["curve_type",b"curve_type"]) -> typing.Optional[typing_extensions.Literal["line_segment"]]: ...
global___CurveSegment = CurveSegment

class Curve(google.protobuf.message.Message):
    """An object similar to a line but that need not be straight."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SEGMENT_FIELD_NUMBER: builtins.int
    @property
    def segment(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CurveSegment]: ...
    def __init__(self,
        *,
        segment: typing.Optional[typing.Iterable[global___CurveSegment]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["segment",b"segment"]) -> None: ...
global___Curve = Curve
