"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import modules.map.proto.map_geometry_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class SpeedControl(google.protobuf.message.Message):
    """This proto defines the format of an auxiliary file that helps to
    define the speed limit on certain area of road.
    Apollo can use this file to quickly fix speed problems on maps,
    instead of waiting for updating map data.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    POLYGON_FIELD_NUMBER: builtins.int
    SPEED_LIMIT_FIELD_NUMBER: builtins.int
    name: typing.Text
    @property
    def polygon(self) -> modules.map.proto.map_geometry_pb2.Polygon: ...
    speed_limit: builtins.float
    def __init__(self,
        *,
        name: typing.Optional[typing.Text] = ...,
        polygon: typing.Optional[modules.map.proto.map_geometry_pb2.Polygon] = ...,
        speed_limit: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["name",b"name","polygon",b"polygon","speed_limit",b"speed_limit"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","polygon",b"polygon","speed_limit",b"speed_limit"]) -> None: ...
global___SpeedControl = SpeedControl

class SpeedControls(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SPEED_CONTROL_FIELD_NUMBER: builtins.int
    @property
    def speed_control(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SpeedControl]: ...
    def __init__(self,
        *,
        speed_control: typing.Optional[typing.Iterable[global___SpeedControl]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["speed_control",b"speed_control"]) -> None: ...
global___SpeedControls = SpeedControls
