"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import modules.map.proto.map_geometry_pb2
import modules.map.proto.map_id_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class YieldSign(google.protobuf.message.Message):
    """A yield indicates that each driver must prepare to stop if necessary to let a
    driver on another approach proceed.
    A driver who stops or slows down to let another vehicle through has yielded
    the right of way to that vehicle.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    STOP_LINE_FIELD_NUMBER: builtins.int
    OVERLAP_ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def stop_line(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_geometry_pb2.Curve]: ...
    @property
    def overlap_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        stop_line: typing.Optional[typing.Iterable[modules.map.proto.map_geometry_pb2.Curve]] = ...,
        overlap_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","overlap_id",b"overlap_id","stop_line",b"stop_line"]) -> None: ...
global___YieldSign = YieldSign
