"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import modules.map.proto.map_clear_area_pb2
import modules.map.proto.map_crosswalk_pb2
import modules.map.proto.map_junction_pb2
import modules.map.proto.map_lane_pb2
import modules.map.proto.map_overlap_pb2
import modules.map.proto.map_parking_space_pb2
import modules.map.proto.map_pnc_junction_pb2
import modules.map.proto.map_road_pb2
import modules.map.proto.map_rsu_pb2
import modules.map.proto.map_signal_pb2
import modules.map.proto.map_speed_bump_pb2
import modules.map.proto.map_stop_sign_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Projection(google.protobuf.message.Message):
    """This message defines how we project the ellipsoidal Earth surface to a plane."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PROJ_FIELD_NUMBER: builtins.int
    proj: typing.Text
    """PROJ.4 setting:
    "+proj=tmerc +lat_0={origin.lat} +lon_0={origin.lon} +k={scale_factor}
    +ellps=WGS84 +no_defs"
    """

    def __init__(self,
        *,
        proj: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["proj",b"proj"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["proj",b"proj"]) -> None: ...
global___Projection = Projection

class Header(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VERSION_FIELD_NUMBER: builtins.int
    DATE_FIELD_NUMBER: builtins.int
    PROJECTION_FIELD_NUMBER: builtins.int
    DISTRICT_FIELD_NUMBER: builtins.int
    GENERATION_FIELD_NUMBER: builtins.int
    REV_MAJOR_FIELD_NUMBER: builtins.int
    REV_MINOR_FIELD_NUMBER: builtins.int
    LEFT_FIELD_NUMBER: builtins.int
    TOP_FIELD_NUMBER: builtins.int
    RIGHT_FIELD_NUMBER: builtins.int
    BOTTOM_FIELD_NUMBER: builtins.int
    VENDOR_FIELD_NUMBER: builtins.int
    version: builtins.bytes
    date: builtins.bytes
    @property
    def projection(self) -> global___Projection: ...
    district: builtins.bytes
    generation: builtins.bytes
    rev_major: builtins.bytes
    rev_minor: builtins.bytes
    left: builtins.float
    top: builtins.float
    right: builtins.float
    bottom: builtins.float
    vendor: builtins.bytes
    def __init__(self,
        *,
        version: typing.Optional[builtins.bytes] = ...,
        date: typing.Optional[builtins.bytes] = ...,
        projection: typing.Optional[global___Projection] = ...,
        district: typing.Optional[builtins.bytes] = ...,
        generation: typing.Optional[builtins.bytes] = ...,
        rev_major: typing.Optional[builtins.bytes] = ...,
        rev_minor: typing.Optional[builtins.bytes] = ...,
        left: typing.Optional[builtins.float] = ...,
        top: typing.Optional[builtins.float] = ...,
        right: typing.Optional[builtins.float] = ...,
        bottom: typing.Optional[builtins.float] = ...,
        vendor: typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bottom",b"bottom","date",b"date","district",b"district","generation",b"generation","left",b"left","projection",b"projection","rev_major",b"rev_major","rev_minor",b"rev_minor","right",b"right","top",b"top","vendor",b"vendor","version",b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bottom",b"bottom","date",b"date","district",b"district","generation",b"generation","left",b"left","projection",b"projection","rev_major",b"rev_major","rev_minor",b"rev_minor","right",b"right","top",b"top","vendor",b"vendor","version",b"version"]) -> None: ...
global___Header = Header

class Map(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADER_FIELD_NUMBER: builtins.int
    CROSSWALK_FIELD_NUMBER: builtins.int
    JUNCTION_FIELD_NUMBER: builtins.int
    LANE_FIELD_NUMBER: builtins.int
    STOP_SIGN_FIELD_NUMBER: builtins.int
    SIGNAL_FIELD_NUMBER: builtins.int
    YIELD_FIELD_NUMBER: builtins.int
    OVERLAP_FIELD_NUMBER: builtins.int
    CLEAR_AREA_FIELD_NUMBER: builtins.int
    SPEED_BUMP_FIELD_NUMBER: builtins.int
    ROAD_FIELD_NUMBER: builtins.int
    PARKING_SPACE_FIELD_NUMBER: builtins.int
    PNC_JUNCTION_FIELD_NUMBER: builtins.int
    RSU_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___Header: ...
    @property
    def crosswalk(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_crosswalk_pb2.Crosswalk]: ...
    @property
    def junction(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_junction_pb2.Junction]: ...
    @property
    def lane(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_lane_pb2.Lane]: ...
    @property
    def stop_sign(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_stop_sign_pb2.StopSign]: ...
    @property
    def signal(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_signal_pb2.Signal]: ...
    @property
    def overlap(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_overlap_pb2.Overlap]: ...
    @property
    def clear_area(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_clear_area_pb2.ClearArea]: ...
    @property
    def speed_bump(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_speed_bump_pb2.SpeedBump]: ...
    @property
    def road(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_road_pb2.Road]: ...
    @property
    def parking_space(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_parking_space_pb2.ParkingSpace]: ...
    @property
    def pnc_junction(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_pnc_junction_pb2.PNCJunction]: ...
    @property
    def rsu(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_rsu_pb2.RSU]: ...
    def __init__(self,
        *,
        header: typing.Optional[global___Header] = ...,
        crosswalk: typing.Optional[typing.Iterable[modules.map.proto.map_crosswalk_pb2.Crosswalk]] = ...,
        junction: typing.Optional[typing.Iterable[modules.map.proto.map_junction_pb2.Junction]] = ...,
        lane: typing.Optional[typing.Iterable[modules.map.proto.map_lane_pb2.Lane]] = ...,
        stop_sign: typing.Optional[typing.Iterable[modules.map.proto.map_stop_sign_pb2.StopSign]] = ...,
        signal: typing.Optional[typing.Iterable[modules.map.proto.map_signal_pb2.Signal]] = ...,
        overlap: typing.Optional[typing.Iterable[modules.map.proto.map_overlap_pb2.Overlap]] = ...,
        clear_area: typing.Optional[typing.Iterable[modules.map.proto.map_clear_area_pb2.ClearArea]] = ...,
        speed_bump: typing.Optional[typing.Iterable[modules.map.proto.map_speed_bump_pb2.SpeedBump]] = ...,
        road: typing.Optional[typing.Iterable[modules.map.proto.map_road_pb2.Road]] = ...,
        parking_space: typing.Optional[typing.Iterable[modules.map.proto.map_parking_space_pb2.ParkingSpace]] = ...,
        pnc_junction: typing.Optional[typing.Iterable[modules.map.proto.map_pnc_junction_pb2.PNCJunction]] = ...,
        rsu: typing.Optional[typing.Iterable[modules.map.proto.map_rsu_pb2.RSU]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header",b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["clear_area",b"clear_area","crosswalk",b"crosswalk","header",b"header","junction",b"junction","lane",b"lane","overlap",b"overlap","parking_space",b"parking_space","pnc_junction",b"pnc_junction","road",b"road","rsu",b"rsu","signal",b"signal","speed_bump",b"speed_bump","stop_sign",b"stop_sign","yield",b"yield"]) -> None: ...
global___Map = Map
