"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import modules.map.proto.map_geometry_pb2
import modules.map.proto.map_id_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Junction(google.protobuf.message.Message):
    """A junction is the junction at-grade of two or more roads crossing."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Junction._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Junction._Type.ValueType  # 0
        IN_ROAD: Junction._Type.ValueType  # 1
        CROSS_ROAD: Junction._Type.ValueType  # 2
        FORK_ROAD: Junction._Type.ValueType  # 3
        MAIN_SIDE: Junction._Type.ValueType  # 4
        DEAD_END: Junction._Type.ValueType  # 5
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    UNKNOWN: Junction.Type.ValueType  # 0
    IN_ROAD: Junction.Type.ValueType  # 1
    CROSS_ROAD: Junction.Type.ValueType  # 2
    FORK_ROAD: Junction.Type.ValueType  # 3
    MAIN_SIDE: Junction.Type.ValueType  # 4
    DEAD_END: Junction.Type.ValueType  # 5

    ID_FIELD_NUMBER: builtins.int
    POLYGON_FIELD_NUMBER: builtins.int
    OVERLAP_ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def polygon(self) -> modules.map.proto.map_geometry_pb2.Polygon: ...
    @property
    def overlap_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    type: global___Junction.Type.ValueType
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        polygon: typing.Optional[modules.map.proto.map_geometry_pb2.Polygon] = ...,
        overlap_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        type: typing.Optional[global___Junction.Type.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","polygon",b"polygon","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","overlap_id",b"overlap_id","polygon",b"polygon","type",b"type"]) -> None: ...
global___Junction = Junction
