"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import modules.common.proto.geometry_pb2
import modules.map.proto.map_geometry_pb2
import modules.map.proto.map_id_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Subsignal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Subsignal._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Subsignal._Type.ValueType  # 1
        CIRCLE: Subsignal._Type.ValueType  # 2
        ARROW_LEFT: Subsignal._Type.ValueType  # 3
        ARROW_FORWARD: Subsignal._Type.ValueType  # 4
        ARROW_RIGHT: Subsignal._Type.ValueType  # 5
        ARROW_LEFT_AND_FORWARD: Subsignal._Type.ValueType  # 6
        ARROW_RIGHT_AND_FORWARD: Subsignal._Type.ValueType  # 7
        ARROW_U_TURN: Subsignal._Type.ValueType  # 8
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    UNKNOWN: Subsignal.Type.ValueType  # 1
    CIRCLE: Subsignal.Type.ValueType  # 2
    ARROW_LEFT: Subsignal.Type.ValueType  # 3
    ARROW_FORWARD: Subsignal.Type.ValueType  # 4
    ARROW_RIGHT: Subsignal.Type.ValueType  # 5
    ARROW_LEFT_AND_FORWARD: Subsignal.Type.ValueType  # 6
    ARROW_RIGHT_AND_FORWARD: Subsignal.Type.ValueType  # 7
    ARROW_U_TURN: Subsignal.Type.ValueType  # 8

    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    type: global___Subsignal.Type.ValueType
    @property
    def location(self) -> modules.common.proto.geometry_pb2.PointENU:
        """Location of the center of the bulb. now no data support."""
        pass
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        type: typing.Optional[global___Subsignal.Type.ValueType] = ...,
        location: typing.Optional[modules.common.proto.geometry_pb2.PointENU] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","location",b"location","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","location",b"location","type",b"type"]) -> None: ...
global___Subsignal = Subsignal

class SignInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SignInfo._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NO_RIGHT_TURN_ON_RED: SignInfo._Type.ValueType  # 1
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    NO_RIGHT_TURN_ON_RED: SignInfo.Type.ValueType  # 1

    TYPE_FIELD_NUMBER: builtins.int
    type: global___SignInfo.Type.ValueType
    def __init__(self,
        *,
        type: typing.Optional[global___SignInfo.Type.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["type",b"type"]) -> None: ...
global___SignInfo = SignInfo

class Signal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Signal._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Signal._Type.ValueType  # 1
        MIX_2_HORIZONTAL: Signal._Type.ValueType  # 2
        MIX_2_VERTICAL: Signal._Type.ValueType  # 3
        MIX_3_HORIZONTAL: Signal._Type.ValueType  # 4
        MIX_3_VERTICAL: Signal._Type.ValueType  # 5
        SINGLE: Signal._Type.ValueType  # 6
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    UNKNOWN: Signal.Type.ValueType  # 1
    MIX_2_HORIZONTAL: Signal.Type.ValueType  # 2
    MIX_2_VERTICAL: Signal.Type.ValueType  # 3
    MIX_3_HORIZONTAL: Signal.Type.ValueType  # 4
    MIX_3_VERTICAL: Signal.Type.ValueType  # 5
    SINGLE: Signal.Type.ValueType  # 6

    ID_FIELD_NUMBER: builtins.int
    BOUNDARY_FIELD_NUMBER: builtins.int
    SUBSIGNAL_FIELD_NUMBER: builtins.int
    OVERLAP_ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    STOP_LINE_FIELD_NUMBER: builtins.int
    SIGN_INFO_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def boundary(self) -> modules.map.proto.map_geometry_pb2.Polygon: ...
    @property
    def subsignal(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Subsignal]: ...
    @property
    def overlap_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]:
        """TODO: add orientation. now no data support."""
        pass
    type: global___Signal.Type.ValueType
    @property
    def stop_line(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_geometry_pb2.Curve]:
        """stop line"""
        pass
    @property
    def sign_info(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SignInfo]: ...
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        boundary: typing.Optional[modules.map.proto.map_geometry_pb2.Polygon] = ...,
        subsignal: typing.Optional[typing.Iterable[global___Subsignal]] = ...,
        overlap_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        type: typing.Optional[global___Signal.Type.ValueType] = ...,
        stop_line: typing.Optional[typing.Iterable[modules.map.proto.map_geometry_pb2.Curve]] = ...,
        sign_info: typing.Optional[typing.Iterable[global___SignInfo]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["boundary",b"boundary","id",b"id","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["boundary",b"boundary","id",b"id","overlap_id",b"overlap_id","sign_info",b"sign_info","stop_line",b"stop_line","subsignal",b"subsignal","type",b"type"]) -> None: ...
global___Signal = Signal
