"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import modules.map.proto.map_geometry_pb2
import modules.map.proto.map_id_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Passage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Passage._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Passage._Type.ValueType  # 0
        ENTRANCE: Passage._Type.ValueType  # 1
        EXIT: Passage._Type.ValueType  # 2
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    UNKNOWN: Passage.Type.ValueType  # 0
    ENTRANCE: Passage.Type.ValueType  # 1
    EXIT: Passage.Type.ValueType  # 2

    ID_FIELD_NUMBER: builtins.int
    SIGNAL_ID_FIELD_NUMBER: builtins.int
    YIELD_ID_FIELD_NUMBER: builtins.int
    STOP_SIGN_ID_FIELD_NUMBER: builtins.int
    LANE_ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def signal_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    @property
    def yield_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    @property
    def stop_sign_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    @property
    def lane_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    type: global___Passage.Type.ValueType
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        signal_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        yield_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        stop_sign_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        lane_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        type: typing.Optional[global___Passage.Type.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","lane_id",b"lane_id","signal_id",b"signal_id","stop_sign_id",b"stop_sign_id","type",b"type","yield_id",b"yield_id"]) -> None: ...
global___Passage = Passage

class PassageGroup(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    PASSAGE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def passage(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Passage]: ...
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        passage: typing.Optional[typing.Iterable[global___Passage]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","passage",b"passage"]) -> None: ...
global___PassageGroup = PassageGroup

class PNCJunction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POLYGON_FIELD_NUMBER: builtins.int
    OVERLAP_ID_FIELD_NUMBER: builtins.int
    PASSAGE_GROUP_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def polygon(self) -> modules.map.proto.map_geometry_pb2.Polygon: ...
    @property
    def overlap_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    @property
    def passage_group(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PassageGroup]: ...
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        polygon: typing.Optional[modules.map.proto.map_geometry_pb2.Polygon] = ...,
        overlap_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        passage_group: typing.Optional[typing.Iterable[global___PassageGroup]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","polygon",b"polygon"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","overlap_id",b"overlap_id","passage_group",b"passage_group","polygon",b"polygon"]) -> None: ...
global___PNCJunction = PNCJunction
