"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import modules.map.proto.map_geometry_pb2
import modules.map.proto.map_id_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class BoundaryEdge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BoundaryEdge._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: BoundaryEdge._Type.ValueType  # 0
        NORMAL: BoundaryEdge._Type.ValueType  # 1
        LEFT_BOUNDARY: BoundaryEdge._Type.ValueType  # 2
        RIGHT_BOUNDARY: BoundaryEdge._Type.ValueType  # 3
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    UNKNOWN: BoundaryEdge.Type.ValueType  # 0
    NORMAL: BoundaryEdge.Type.ValueType  # 1
    LEFT_BOUNDARY: BoundaryEdge.Type.ValueType  # 2
    RIGHT_BOUNDARY: BoundaryEdge.Type.ValueType  # 3

    CURVE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    @property
    def curve(self) -> modules.map.proto.map_geometry_pb2.Curve: ...
    type: global___BoundaryEdge.Type.ValueType
    def __init__(self,
        *,
        curve: typing.Optional[modules.map.proto.map_geometry_pb2.Curve] = ...,
        type: typing.Optional[global___BoundaryEdge.Type.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["curve",b"curve","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["curve",b"curve","type",b"type"]) -> None: ...
global___BoundaryEdge = BoundaryEdge

class BoundaryPolygon(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EDGE_FIELD_NUMBER: builtins.int
    @property
    def edge(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BoundaryEdge]: ...
    def __init__(self,
        *,
        edge: typing.Optional[typing.Iterable[global___BoundaryEdge]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["edge",b"edge"]) -> None: ...
global___BoundaryPolygon = BoundaryPolygon

class RoadBoundary(google.protobuf.message.Message):
    """boundary with holes"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OUTER_POLYGON_FIELD_NUMBER: builtins.int
    HOLE_FIELD_NUMBER: builtins.int
    @property
    def outer_polygon(self) -> global___BoundaryPolygon: ...
    @property
    def hole(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BoundaryPolygon]:
        """if boundary without hole, hole is null"""
        pass
    def __init__(self,
        *,
        outer_polygon: typing.Optional[global___BoundaryPolygon] = ...,
        hole: typing.Optional[typing.Iterable[global___BoundaryPolygon]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["outer_polygon",b"outer_polygon"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["hole",b"hole","outer_polygon",b"outer_polygon"]) -> None: ...
global___RoadBoundary = RoadBoundary

class RoadROIBoundary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    ROAD_BOUNDARIES_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def road_boundaries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RoadBoundary]: ...
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        road_boundaries: typing.Optional[typing.Iterable[global___RoadBoundary]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","road_boundaries",b"road_boundaries"]) -> None: ...
global___RoadROIBoundary = RoadROIBoundary

class RoadSection(google.protobuf.message.Message):
    """road section defines a road cross-section, At least one section must be
    defined in order to
    use a road, If multiple road sections are defined, they must be listed in
    order along the road
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    LANE_ID_FIELD_NUMBER: builtins.int
    BOUNDARY_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def lane_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]:
        """lanes contained in this section"""
        pass
    @property
    def boundary(self) -> global___RoadBoundary:
        """boundary of section"""
        pass
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        lane_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        boundary: typing.Optional[global___RoadBoundary] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["boundary",b"boundary","id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["boundary",b"boundary","id",b"id","lane_id",b"lane_id"]) -> None: ...
global___RoadSection = RoadSection

class Road(google.protobuf.message.Message):
    """The road is a collection of traffic elements, such as lanes, road boundary
    etc.
    It provides general information about the road.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Road._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: Road._Type.ValueType  # 0
        HIGHWAY: Road._Type.ValueType  # 1
        CITY_ROAD: Road._Type.ValueType  # 2
        PARK: Road._Type.ValueType  # 3
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    UNKNOWN: Road.Type.ValueType  # 0
    HIGHWAY: Road.Type.ValueType  # 1
    CITY_ROAD: Road.Type.ValueType  # 2
    PARK: Road.Type.ValueType  # 3

    ID_FIELD_NUMBER: builtins.int
    SECTION_FIELD_NUMBER: builtins.int
    JUNCTION_ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def section(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RoadSection]: ...
    @property
    def junction_id(self) -> modules.map.proto.map_id_pb2.Id:
        """if lane road not in the junction, junction id is null."""
        pass
    type: global___Road.Type.ValueType
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        section: typing.Optional[typing.Iterable[global___RoadSection]] = ...,
        junction_id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        type: typing.Optional[global___Road.Type.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","junction_id",b"junction_id","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","junction_id",b"junction_id","section",b"section","type",b"type"]) -> None: ...
global___Road = Road
