"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import modules.map.proto.map_geometry_pb2
import modules.map.proto.map_id_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ParkingSpace(google.protobuf.message.Message):
    """ParkingSpace is a place designated to park a car."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POLYGON_FIELD_NUMBER: builtins.int
    OVERLAP_ID_FIELD_NUMBER: builtins.int
    HEADING_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def polygon(self) -> modules.map.proto.map_geometry_pb2.Polygon: ...
    @property
    def overlap_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    heading: builtins.float
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        polygon: typing.Optional[modules.map.proto.map_geometry_pb2.Polygon] = ...,
        overlap_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        heading: typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["heading",b"heading","id",b"id","polygon",b"polygon"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["heading",b"heading","id",b"id","overlap_id",b"overlap_id","polygon",b"polygon"]) -> None: ...
global___ParkingSpace = ParkingSpace

class ParkingLot(google.protobuf.message.Message):
    """ParkingLot is a place for parking cars."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POLYGON_FIELD_NUMBER: builtins.int
    OVERLAP_ID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def polygon(self) -> modules.map.proto.map_geometry_pb2.Polygon: ...
    @property
    def overlap_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        polygon: typing.Optional[modules.map.proto.map_geometry_pb2.Polygon] = ...,
        overlap_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","polygon",b"polygon"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","overlap_id",b"overlap_id","polygon",b"polygon"]) -> None: ...
global___ParkingLot = ParkingLot
