"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import modules.map.proto.map_geometry_pb2
import modules.map.proto.map_id_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class StopSign(google.protobuf.message.Message):
    """A stop sign is a traffic sign to notify drivers that they must stop before
    proceeding.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _StopType:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _StopTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StopSign._StopType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        UNKNOWN: StopSign._StopType.ValueType  # 0
        ONE_WAY: StopSign._StopType.ValueType  # 1
        TWO_WAY: StopSign._StopType.ValueType  # 2
        THREE_WAY: StopSign._StopType.ValueType  # 3
        FOUR_WAY: StopSign._StopType.ValueType  # 4
        ALL_WAY: StopSign._StopType.ValueType  # 5
    class StopType(_StopType, metaclass=_StopTypeEnumTypeWrapper):
        pass

    UNKNOWN: StopSign.StopType.ValueType  # 0
    ONE_WAY: StopSign.StopType.ValueType  # 1
    TWO_WAY: StopSign.StopType.ValueType  # 2
    THREE_WAY: StopSign.StopType.ValueType  # 3
    FOUR_WAY: StopSign.StopType.ValueType  # 4
    ALL_WAY: StopSign.StopType.ValueType  # 5

    ID_FIELD_NUMBER: builtins.int
    STOP_LINE_FIELD_NUMBER: builtins.int
    OVERLAP_ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> modules.map.proto.map_id_pb2.Id: ...
    @property
    def stop_line(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_geometry_pb2.Curve]: ...
    @property
    def overlap_id(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[modules.map.proto.map_id_pb2.Id]: ...
    type: global___StopSign.StopType.ValueType
    def __init__(self,
        *,
        id: typing.Optional[modules.map.proto.map_id_pb2.Id] = ...,
        stop_line: typing.Optional[typing.Iterable[modules.map.proto.map_geometry_pb2.Curve]] = ...,
        overlap_id: typing.Optional[typing.Iterable[modules.map.proto.map_id_pb2.Id]] = ...,
        type: typing.Optional[global___StopSign.StopType.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","overlap_id",b"overlap_id","stop_line",b"stop_line","type",b"type"]) -> None: ...
global___StopSign = StopSign
